name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]

  workflow_dispatch:
  repository_dispatch:

env:
  REPO_URL: https:\/\/siansiansu.github.io
  DESCRIPTION: 台語學習資源清單 Tâi-gí ha̍k-si̍p chu-guân tshing-tuann

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone
        uses: actions/checkout@v3
        with:
          repository: siansiansu/jekyll-theme
          path: jekyll-theme

      - name: Run
        run: |
          cp -r jekyll-theme/* .
          sed -i "3s/.*/url: ${REPO_URL}/" _config.yml
          sed -i "4s/.*/description: ${DESCRIPTION}/" _config.yml
          sed -i '1 i---\nlayout: home\n---\n' README.md
          cp README.md index.md

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
